version: '2.1'

services:
  product:
    image: product-service:1.0.0-SNAPSHOT
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation:
    image: recommendation-service:1.0.0-SNAPSHOT
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    image: review-service:1.0.0-SNAPSHOT
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    image: product-composite-service:1.0.0-SNAPSHOT
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
